#error (2:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario Outline: Add items to do list'
#error (3:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Given I am on <website>'
#error (4:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'And I add <Item> in the text box'
#error (5:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'When I press enter'
#error (6:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Then I see <Item> added to the list'
#error (7:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'And I see a radio button infront of each <item> in the list'
#error (8:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'And I see number of items left'
#error (9:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'And I see All Button is hightlighted'
#error (10:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'And I see Active button'
#error (11:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'And I see Completed button'
#error (12:2): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Examples:'